
#pragma once

enum RESULT_CODE : u32
{
	RESULT_CODE_SUCCESS,
	RESULT_CODE_FAILED_MEMORY_ARENA_INITIALISATION,
	RESULT_CODE_UNKNOWN_OPTIONAL_COMMAND,
	RESULT_CODE_FAILED_TO_OPEN_INPUT_DATA_FILE,
	RESULT_CODE_UNKNOWN_EXTENSION,
	RESULT_CODE_PARSE_DATA_FILE_UNSUPPORTED,
	RESULT_CODE_PARSE_DATA_FILE_FAILED,
	RESULT_CODE_PARSE_DATA_FILE_FAILED_TO_READ_FILE,
	RESULT_CODE_FAILED_TO_OPEN_INPUT_FILE,
	RESULT_CODE_FAILED_TO_CREATE_OUTPUT_FILE,
	RESULT_CODE_FAILED_TO_CREATE_OUTPUT_DATA_FILE,
	RESULT_CODE_FAILED_TO_ALLOCATE_MEMORY_FOR_OUTPUT_IMAGE,
	RESULT_CODE_FAILED_TO_OPEN_OUTPUT_FILE,
	RESULT_CODE_FAILED_TO_INJECT_IMAGE,
};

static inline const char *error_code_string( RESULT_CODE code )
{
	switch ( code )
	{
	case RESULT_CODE_SUCCESS: return "RESULT_CODE_SUCCESS";
	case RESULT_CODE_FAILED_MEMORY_ARENA_INITIALISATION: return "RESULT_CODE_FAILED_MEMORY_ARENA_INITIALISATION";
	case RESULT_CODE_UNKNOWN_OPTIONAL_COMMAND: return "RESULT_CODE_UNKNOWN_OPTIONAL_COMMAND";
	case RESULT_CODE_FAILED_TO_OPEN_INPUT_DATA_FILE: return "RESULT_CODE_FAILED_TO_OPEN_INPUT_DATA_FILE";
	case RESULT_CODE_UNKNOWN_EXTENSION: return "RESULT_CODE_UNKNOWN_EXTENSION";
	case RESULT_CODE_PARSE_DATA_FILE_UNSUPPORTED: return "RESULT_CODE_PARSE_DATA_FILE_UNSUPPORTED";
	case RESULT_CODE_PARSE_DATA_FILE_FAILED: return "RESULT_CODE_PARSE_DATA_FILE_FAILED";
	case RESULT_CODE_PARSE_DATA_FILE_FAILED_TO_READ_FILE: return "RESULT_CODE_PARSE_DATA_FILE_FAILED_TO_READ_FILE";
	case RESULT_CODE_FAILED_TO_OPEN_INPUT_FILE: return "RESULT_CODE_FAILED_TO_OPEN_INPUT_FILE";
	case RESULT_CODE_FAILED_TO_CREATE_OUTPUT_FILE: return "RESULT_CODE_FAILED_TO_CREATE_OUTPUT_FILE";
	case RESULT_CODE_FAILED_TO_CREATE_OUTPUT_DATA_FILE: return "RESULT_CODE_FAILED_TO_CREATE_OUTPUT_DATA_FILE";
	case RESULT_CODE_FAILED_TO_ALLOCATE_MEMORY_FOR_OUTPUT_IMAGE: return "RESULT_CODE_FAILED_TO_ALLOCATE_MEMORY_FOR_OUTPUT_IMAGE";
	case RESULT_CODE_FAILED_TO_OPEN_OUTPUT_FILE: return "RESULT_CODE_FAILED_TO_OPEN_OUTPUT_FILE";
	case RESULT_CODE_FAILED_TO_INJECT_IMAGE: return "RESULT_CODE_FAILED_TO_INJECT_IMAGE";
	}

	return "UNKNOWN ERROR CODE";
}