
#
# Build Workflow
#

name: Build-Windows

run-name: ${{ github.actor }} started a windows build.

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - third_party/**
      - CMakeLists.txt
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - third_party/**
      - CMakeLists.txt
      - .github/workflows/**

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Dependencies
      - name: Install zlib
        run: |
          vcpkg install zlib:x64-windows-static

      # Build static-mt
      - name: Create Build System (static-mt)
        run: >
          cmake -S . -B build/static-mt -G"Visual Studio 17 2022"
          -DBUILD_STATIC=ON
          -DBUILD_CRT_STATIC=ON
          -DLINK_ZLIB="C:/vcpkg/packages/zlib_x64-windows-static"
          -DLINK_ZLIB_INCLUDE="include/"
          -DLINK_ZLIB_LIB="lib/zlib.lib"
          -DLINK_ZLIB_LIB_DEBUG="debug/lib/zlibd.lib"

      - name: Build Project (static-mt)
        run: cmake --build build/static-mt --config Release

      # Upload Artifacts
      - name: Upload Static Release MT Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-mt-release
          path: build/builds/bin-static-mt-release/