
#
# Build Workflow
#

name: Build-Ubuntu

run-name: ${{ github.actor }} started a ubuntu build.

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - third_party/**
      - CMakeLists.txt
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - third_party/**
      - CMakeLists.txt
      - .github/workflows/**

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Dependencies
      - name: Install zlib
        run: |
          vcpkg install zlib:x64-linux-release

      # Build static-mt
      - name: Create Build System (static-mt)
        run: >
          cmake -S . -B build/static-mt
          -DBUILD_STATIC=ON
          -DBUILD_CRT_STATIC=ON
          -DLINK_ZLIB=/usr/local/share/vcpkg/packages/zlib_x64-linux-release
          -DLINK_ZLIB_INCLUDE=include/
          -DLINK_ZLIB_LIB=lib/zlib.lib
          -DLINK_ZLIB_LIB_DEBUG=debug/lib/zlibd.lib

      - name: Build Project (static-mt)
        run: cmake --build build/static-mt --config=Release

      # Upload Artifacts
      - name: Upload Static Release MT Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-mt-release
          path: build/builds/bin-static-mt-release/